### ISSUE TITLE
[PROPOSAL] Add Bake Time

### ISSUE THREAD

**Issue by dblock** [opensearch-project/community#52]
### What are you proposing?

This repo documents things like the TSC/GB and should be edited carefully. I propose we add Bake Time like in https://github.com/opensearch-project/.github/blob/main/.github/workflows/bake_time.yml so that changes sit for 48 hours without comment before getting merged.

### What problems are you trying to solve?

Avoid rushed changes that may require more discussion to undo. 

### What is the developer experience going to be?

Every PR will sit for 48 hours before getting merged.

**Comment by krisfreedain** [comment]
I agree for the TSC/GB pieces, but it will definitely add challenges for the other items we use this repo for - presentations, community docs, etc. Interested in your thoughts on that.

**Comment by dblock** [comment]
We can probably include/exclude some folders, https://github.com/peternied/bake-time/issues/11.

**Comment by krisfreedain** [comment]
I like that idea a lot - include the two folders we're building for the governing-board & technical-steering-committee - would only slow down the ability to post meeting minutes, but that is a good balance.

**Comment by krisfreedain** [comment]
Since we've moved the TSC / GB pieces over to a more appropriate home - this becomes unnecessary.

**Comment by dblock** [comment]
@krisfreedain If you don't think we need it here please feel free to close
